### ISSUE TITLE
dll lst

### ISSUE THREAD

**Issue by sec13b** [kevinLyon/HookScanner#1]
no offense , can you add a complete  all variables can be used for PCHAR list who can hook almost EDR

PCHAR* pcLoot[] = { ntdll_lst, kernel32_lst };

thank you

**Comment by sec13b** [comment]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
gcc HookerScanner.c -o HookerScanner.exe
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HookerScanner.c:1:10: fatal error: Windows.h: No such file or directory
    1 | #include <Windows.h>
      |          ^~~~~~~~~~~
compilation terminated.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 x86_64-w64-mingw32-gcc HookerScanner.c  -o HookerScanner.exe
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

HookerScanner.c:1:10: fatal error: Windows.h: No such file or directory
    1 | #include <Windows.h>
      |          ^~~~~~~~~~~
compilation terminated.


~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by kevinLyon** [comment]
Thanks for the report. It's fixed now, and you can compile again using x86_64-w64-mingw32-gcc.

Regarding the DLL lists, the most common ones hooked by EDRs are ntdll.dll and kernel32.dll. I highly recommend a straightforward approach: if you use VirtualAlloc in your malware, then look for hooks in the DLL that provides this function, such as kernel32.dll. Similarly, if you use NtQueueApcThreadEx, check ntdll.dll (the provider), and so on.
